params:
  imageConvertTo: webp
  imageLoading: lazy
  imageAddClass: img-fluid
  imageResponsive: true
  imageSizesAttr: 100vw
module:
  imports:
    - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
    - path: github.com/gohugoio/hugo-mod-jslibs/turbo/v7
    - path: github.com/lkhrs/image-handling-mod-hugo-dfd